//
//  StyleKitName.h
//  LCDClock
//
//  Created by Vladyslav Gusakov on 1/25/16.
//  Copyright (c) 2016 vlgusakov. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface StyleKitName : NSObject

// Drawing Methods
+ (void)drawCanvas1;

@end
