//
//  StyleKitName.m
//  LCDClock
//
//  Created by Vladyslav Gusakov on 1/25/16.
//  Copyright (c) 2016 vlgusakov. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "StyleKitName.h"


@implementation StyleKitName

#pragma mark Initialization

+ (void)initialize
{
}

#pragma mark Drawing Methods

+ (void)drawCanvas1
{
    //// General Declarations
    CGContextRef context = UIGraphicsGetCurrentContext();

    //// Color Declarations
    UIColor* color = [UIColor colorWithRed: 1 green: 0 blue: 0 alpha: 1];
    UIColor* color2 = [UIColor colorWithRed: 0 green: 0 blue: 0 alpha: 1];

    //// Bezier Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, 104.49, 16.03);
    CGContextRotateCTM(context, 4.33 * M_PI / 180);

    UIBezierPath* bezierPath = [UIBezierPath bezierPath];
    [bezierPath moveToPoint: CGPointMake(4.73, -0)];
    [bezierPath addLineToPoint: CGPointMake(0, 6.82)];
    [bezierPath addLineToPoint: CGPointMake(0, 27.27)];
    [bezierPath addLineToPoint: CGPointMake(4.73, 34.62)];
    [bezierPath addLineToPoint: CGPointMake(9.46, 27.27)];
    [bezierPath addLineToPoint: CGPointMake(9.46, 6.82)];
    [bezierPath addLineToPoint: CGPointMake(4.73, -0)];
    [bezierPath closePath];
    [color setFill];
    [bezierPath fill];
    [color2 setStroke];
    bezierPath.lineWidth = 1;
    [bezierPath stroke];

    CGContextRestoreGState(context);
}

@end
